// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: tweet.proto

package tweet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTweetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *GetTweetsRequest) Reset() {
	*x = GetTweetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tweet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTweetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetsRequest) ProtoMessage() {}

func (x *GetTweetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tweet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetsRequest.ProtoReflect.Descriptor instead.
func (*GetTweetsRequest) Descriptor() ([]byte, []int) {
	return file_tweet_proto_rawDescGZIP(), []int{0}
}

func (x *GetTweetsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetTweetsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time    []string `protobuf:"bytes,1,rep,name=Time,proto3" json:"Time,omitempty"`
	Text    []string `protobuf:"bytes,2,rep,name=Text,proto3" json:"Text,omitempty"`
	User    []string `protobuf:"bytes,3,rep,name=User,proto3" json:"User,omitempty"`
	Success bool     `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *GetTweetsResponse) Reset() {
	*x = GetTweetsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tweet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTweetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetsResponse) ProtoMessage() {}

func (x *GetTweetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tweet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetsResponse.ProtoReflect.Descriptor instead.
func (*GetTweetsResponse) Descriptor() ([]byte, []int) {
	return file_tweet_proto_rawDescGZIP(), []int{1}
}

func (x *GetTweetsResponse) GetTime() []string {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *GetTweetsResponse) GetText() []string {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *GetTweetsResponse) GetUser() []string {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetTweetsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PostTweetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Text     string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *PostTweetRequest) Reset() {
	*x = PostTweetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tweet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTweetRequest) ProtoMessage() {}

func (x *PostTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tweet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTweetRequest.ProtoReflect.Descriptor instead.
func (*PostTweetRequest) Descriptor() ([]byte, []int) {
	return file_tweet_proto_rawDescGZIP(), []int{2}
}

func (x *PostTweetRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PostTweetRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PostTweetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PostTweetResponse) Reset() {
	*x = PostTweetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tweet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTweetResponse) ProtoMessage() {}

func (x *PostTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tweet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTweetResponse.ProtoReflect.Descriptor instead.
func (*PostTweetResponse) Descriptor() ([]byte, []int) {
	return file_tweet_proto_rawDescGZIP(), []int{3}
}

func (x *PostTweetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_tweet_proto protoreflect.FileDescriptor

var file_tweet_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74,
	0x77, 0x65, 0x65, 0x74, 0x22, 0x2e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x69, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x54, 0x65, 0x78,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22,
	0x42, 0x0a, 0x10, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x22, 0x2d, 0x0a, 0x11, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x32, 0x92, 0x01, 0x0a, 0x0c, 0x54, 0x77, 0x65, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x73,
	0x12, 0x17, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x77, 0x65, 0x65,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74, 0x77, 0x65, 0x65,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x09, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x77, 0x65,
	0x65, 0x74, 0x12, 0x17, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x54,
	0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74, 0x77,
	0x65, 0x65, 0x74, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x74, 0x77, 0x65,
	0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tweet_proto_rawDescOnce sync.Once
	file_tweet_proto_rawDescData = file_tweet_proto_rawDesc
)

func file_tweet_proto_rawDescGZIP() []byte {
	file_tweet_proto_rawDescOnce.Do(func() {
		file_tweet_proto_rawDescData = protoimpl.X.CompressGZIP(file_tweet_proto_rawDescData)
	})
	return file_tweet_proto_rawDescData
}

var file_tweet_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tweet_proto_goTypes = []interface{}{
	(*GetTweetsRequest)(nil),  // 0: tweet.GetTweetsRequest
	(*GetTweetsResponse)(nil), // 1: tweet.GetTweetsResponse
	(*PostTweetRequest)(nil),  // 2: tweet.PostTweetRequest
	(*PostTweetResponse)(nil), // 3: tweet.PostTweetResponse
}
var file_tweet_proto_depIdxs = []int32{
	0, // 0: tweet.TweetService.GetTweets:input_type -> tweet.GetTweetsRequest
	2, // 1: tweet.TweetService.PostTweet:input_type -> tweet.PostTweetRequest
	1, // 2: tweet.TweetService.GetTweets:output_type -> tweet.GetTweetsResponse
	3, // 3: tweet.TweetService.PostTweet:output_type -> tweet.PostTweetResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tweet_proto_init() }
func file_tweet_proto_init() {
	if File_tweet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tweet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTweetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tweet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTweetsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tweet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostTweetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tweet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostTweetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tweet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tweet_proto_goTypes,
		DependencyIndexes: file_tweet_proto_depIdxs,
		MessageInfos:      file_tweet_proto_msgTypes,
	}.Build()
	File_tweet_proto = out.File
	file_tweet_proto_rawDesc = nil
	file_tweet_proto_goTypes = nil
	file_tweet_proto_depIdxs = nil
}
